services:
  blog:
    image: nginx:alpine
    container_name: blog
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
